routes/web.php
<?php

use App\Http\Controllers\RegisteredTenantController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', static function () {
    return view('welcome');
});


Route::get('register', [RegisteredTenantController::class, 'create'])
    ->name('register');

Route::post('register', [RegisteredTenantController::class, 'store']);

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;


    protected $fillable = ['name', 'email', 'message', 'tenant_id'];


    public function tenant(): void
    {
        $this->belongsTo(Tenant::class);
    }

    public function service(): void
    {
        $this->hasMany(Service::class, 'service_id');
    }
}

app/Models/Tenant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\Database\Concerns\HasDatabase;
use Stancl\Tenancy\Database\Concerns\HasDomains;
use Stancl\Tenancy\Database\Models\Tenant as ModelsTenant;
use Stancl\Tenancy\DatabaseConfig;

class Tenant extends ModelsTenant implements TenantWithDatabase
{
    use HasFactory;

    use HasDatabase;

    use HasDomains;

    public static function booted()
    {
        static::creating(function ($tenant) {
            $tenant->password = bcrypt($tenant->password);
        });
    }


    public function contacts()
    {
        $this->hasMany(Contact::class);
    }
}

app/Http/Controllers/TenantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TenantController extends Controller
{

    public function index(): \Illuminate\Contracts\View\View|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\Foundation\Application
    {

        return view('tenant.index');
    }

}

app/View/Components/TenantsLayout.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class TenantsLayout extends Component
{
    /**
     * Create a new component instance.
     */


    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View
    {
        return view('layouts.tenants');
    }
}

resources/views/tenant/contact/create.blade.php
<x-tenants-layout>

    <!-- Contact Section -->
    <section class="container mx-auto p-6 mt-6">
        <h2 class="text-3xl font-semibold mb-4 text-center">Contact Us</h2>


        {{--  @if ($errors->any())
              <div class="text-red-600">
                  <ul>
                      @foreach ($errors->all() as $error)
                          <li>{{ $error }}</li>
                      @endforeach
                  </ul>
              </div>
          @endif--}}
        <div class="bg-white shadow-md rounded-lg p-6">
            <form action="{{ route('tenant.contact.store') }}" method="POST">
                @csrf
                <div class="mb-4">
                    <label for="name" class="block text-gray-700">Name</label>
                    <input
                        type="text"
                        id="name"
                        name="name"
                        value="{{ old('name') }}"
                        class="@error('name') border-red-700 @enderror w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600"
                    >

                    @error('name')
                    <div class="text-red-700">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-4">
                    <label for="email" class="block text-gray-700">Email</label>
                    <input
                        type="email"
                        id="email" name="email"
                        value="{{ old('email') }}"
                        class=" @error('email')  border-red-700 @enderror w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600"
                    >

                    @error('email')
                    <div class="text-red-700">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-4">
                    <label for="message" class="block text-gray-700">Message</label>
                    <textarea
                        id="message"
                        name="message"
                        class="@error('message') border-red-700 @enderror w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600"
                        rows="4"
                    >
                        {{ old('message') }}
                    </textarea>

                    @error('message')
                    <div class="text-red-700">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="w-full bg-blue-800 text-white py-2 rounded-lg hover:bg-blue-700">Send Message</button>
            </form>
        </div>
    </section>


</x-tenants-layout>